<?php

return [
	'bots' => [ // Bot names
		'mail.ru',
		'yandex.com/bots',
		'rambler',
		'googlebot',
		'bing.com',
		'webvisor',
		'dotnetdotcom',
		'libwww-perl',
		'python-urllib',
		'telegrambot',
		'twitterbot',
		'statdom.ru',
		'aport',
		'yahoo',
		'msnbot',
		'turtle',
		'omsktele',
		'yetibot',
		'picsearch',
		'sape.bot',
		'sape_context',
		'gigabot',
		'snapbot',
		'alexa.com',
		'megadownload.net',
		'askpeter.info',
		'igde.ru',
		'ask.com',
		'qwartabot',
		'yanga.co.uk',
		'scoutjet',
		'similarpages',
		'oozbot',
		'shrinktheweb.com',
		'aboutusbot',
		'followsite.com',
		'dataparksearch',
		'google-sitemaps',
		'appengine-google',
		'feedfetcher-google',
		'liveinternet.ru',
		'xml-sitemaps.com',
		'agama',
		'metadatalabs.com',
		'h1.hrn.ru',
		'googlealert.com',
		'seo-rus.com',
		'copyscape.com',
		'adsbot-google',
		'domaintools.com',
		'nigma.ru'
	],
	'mobile_clients' => [ // Mobile client names
		'ipad',
		'iphone',
		'android',
		'pocket',
		'palm',
		'windows ce',
		'windowsce',
		'cellphone',
		'opera mobi',
		'ipod',
		'small',
		'sharp',
		'sonyericsson',
		'symbian',
		'opera mini',
		'nokia',
		'htc_',
		'samsung',
		'motorola',
		'smartphone',
		'blackberry',
		'playstation portable',
		'tablet browser'
	]
];
